version: '3.8'
services:
  todo-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
